blueprint:
  name: TODO
  description: TODO
  source_url: https://github.com/lymanepp/homeassistant-blueprints/blob/main/homeseer-status-led.yaml
  domain: automation
  input:
    zwavejs_device_id:
      name: Z-Wave JS switch
      description: Select the sensor device which offers scene selection.
        Listed devices are not guaranteed to work with any/all of these button mappings.
      selector:
        target:
          device:
            integration: zwave_js
    current_state:
      name: Windows are open
      description: TODO
      selector:
        entity:
    expected_state:
      name: Windows can be open
      description: TODO
      selector:
        entity:

variables:
  zwavejs_device_id: !input "zwavejs_device_id"
  current_state: !input "current_state"
  expected_state: !input "expected_state"

trigger:
  - platform: state
    entity_id: !input "current_state"
  - platform: state
    entity_id: !input "expected_state"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ states(current_state) == states(expected_state) }}
        sequence:
          - service: zwave_js.set_config_parameter
            target:
              device_id: !input "zwavejs_device_id"
            data:
              parameter: "23"
              value: "0"
          - service: zwave_js.set_config_parameter
            target:
              device_id: !input "zwavejs_device_id"
            data:
              parameter: "31"
              value: "0"
              bitmask: "4"
    default:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ states(expected_state) == "on" }}
            sequence:
              - service: zwave_js.set_config_parameter
                target:
                  device_id: !input "zwavejs_device_id"
                data:
                  parameter: "23"
                  value: "2"
        default:
          - service: zwave_js.set_config_parameter
            target:
              device_id: !input "zwavejs_device_id"
            data:
              parameter: "23"
              value: "1"
      - service: zwave_js.set_config_parameter
        target:
          device_id: !input "zwavejs_device_id"
        data:
          parameter: "31"
          value: "1"
          bitmask: "4"
      - service: zwave_js.set_config_parameter
        target:
          device_id: !input "zwavejs_device_id"
        data:
          parameter: "13"
          value: "1"
mode: single
