blueprint:
  name: Leak detection & notifier
  description: Send a notification when any configured moisture sensor becomes moist
  source_url: https://github.com/lymanepp/ha-blueprints/blob/main/leak-detected.yaml
  domain: automation
  input:
    leak_sensors:
      name: Leak Sensors
      description: TODO
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
    shutoff_valve:
      name: (OPTIONAL) Water shutoff valve
      description: TODO
      selector:
        entity:
          domain: switch
      default: []
    notify_action:
      name: (OPTIONAL) Notify action
      description: TODO
      selector:
        action:
      default: []

mode: parallel
max: 10

trigger:
  - platform: state
    entity_id: !input leak_sensors
    to: 'on'

variables:
  shutoff_valve: !input "shutoff_valve"
  notify_action: !input "notify_action"

condition: []

action:
  - choose: []
    default: !input "actions"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ shutoff_valve != none }}'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input "shutoff_valve"
        default: []
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ notify_action != none }}'
        sequence: !input "notify_action"
        default: []
